name: ticktrack

packages:
  - .

command:
  version:
    # Restrict `melos version` to the trunk branch.
    branch: main
    workspaceChangelog: false
    includeCommitId: true
    changelogFormat:
      includeDate: true
